fragment Image on File {
  id
  url
  metadata
}

fragment CompanyType on CompanyType {
  id
  key
  value
  isDefault
}

fragment CompanySize on CompanySize {
  id
  key
  value
  isDefault
}

fragment UserOnly on UserOnly {
  id
  avatarUrl
  avatar {
    ...Image
  }
  firstName
  lastName
  email
  color
  addressDetail
  # address {
  #   city {
  #     id
  #     name
  #     countryName
  #     countryId
  #     stateName
  #     stateId
  #   }
  # }
  phoneNumber
  role
  createdAt
  updatedAt
}

fragment User on User {
  id
  avatarUrl
  avatar {
    ...Image
  }
  firstName
  lastName
  email
  color
  addressDetail
  # address {
  #   city {
  #     id
  #     name
  #     countryName
  #     countryId
  #     stateName
  #     stateId
  #   }
  # }
  phoneNumber
  role
  createdAt
  updatedAt
}

fragment UserFragment on UserOnly {
  id
  avatarUrl
  firstName
  lastName
  email
  color
  addressDetail
  phoneNumber
  role
  createdAt
  updatedAt
  status
}
fragment Metadata on Metadata {
  page
  total
  limit
}
fragment SkillFragment on Skill {
  id
  content
  createdAt
  deletedAt
  updatedAt
}

fragment JobFragment on Job {
  id
  jobTitle {
    name
  }
  type
  salary
  addressDetail
  description
  numberOfRecruits
  applicationDeadline
  maxSalary
  minSalary
  isBoot
  company {
    id
    name
    avatar {
      url
    }
    type {
      key
    }
    size {
      key
    }
  }
  skills {
    id
    content
  }
  level
  address {
    id
    name
    stateName
    countryName
  }
  jobCategory {
    id
    name
  }
  salaryMetadata
  createdAt
  updatedAt
  deletedAt
}
