query allLanguageSkill(
  $where: LanguageSkillWhereInput
  $pagination: PaginationInput
  $searchValue: String
  $orderBy: [LanguageSkillOrderByWithRelationInput!]
) {
  all_language_skill(
    where: $where
    pagination: $pagination
    searchValue: $searchValue
    orderBy: $orderBy
  ) {
    data {
      id
      name
      locale
      proficiencyLevel
      createdAt
      updatedAt
    }
    metadata {
      total
      limit
      page
    }
  }
}

query allLanguage(
  $where: LanguageWhereInput
  $pagination: PaginationInput
  $searchValue: String
  $orderBy: [LanguageOrderByWithRelationInput!]
) {
  all_language(
    where: $where
    pagination: $pagination
    searchValue: $searchValue
    orderBy: $orderBy
  ) {
    data {
      id
      name
      locale
      createdAt
      updatedAt
    }
    metadata {
      total
      limit
      page
    }
  }
}
