query allSkill(
  $where: SkillWhereInput
  $orderBy: [SkillOrderByWithRelationInput!]
  $searchValue: String
  $pagination: PaginationInput
) {
  all_skill(where: $where, orderBy: $orderBy, searchValue: $searchValue, pagination: $pagination) {
    data {
      ...SkillFragment
    }
    metadata {
      ...Metadata
    }
  }
}

mutation deleteWorkingSkill($where: SkillWhereUniqueInput!) {
  delete_skill(where: $where) {
    ...SkillFragment
  }
}

mutation createSkill($data: SkillCreateInput!) {
  create_skill(data: $data) {
    content
    createdAt
    updatedAt
    deletedAt
  }
}

mutation updateSkill($data: SkillUpdateInput!, $where: SkillWhereUniqueInput!) {
  update_skill(data: $data, where: $where) {
    content
    createdAt
    updatedAt
    deletedAt
  }
}

query oneSkill($where: SkillWhereInput!) {
  one_skill(where: $where) {
    ...SkillFragment
  }
}
