mutation createResume(
  $resumeTemplateName: ResumeTemplate!
  $personalInfo: ResumePersonalInfo!
  $workExperiences: [ResumeWorkExperience!]! = []
  $projects: [ResumeProject!] = []
  $educations: [ResumeEducation!] = []
  $languageSkillIds: [String!] = []
  $skillIds: [String!] = []
  $certificates: [ResumeCertificate!] = []
  $socials: [ResumeSocial!] = []
  $activities: [ResumeActivity!] = []
  $userId: String
) {
  create_resume(
    resumeTemplateName: $resumeTemplateName
    personalInfo: $personalInfo
    workExperiences: $workExperiences
    projects: $projects
    educations: $educations
    languageSkillIds: $languageSkillIds
    skillIds: $skillIds
    certificates: $certificates
    socials: $socials
    activities: $activities
    userId: $userId
  ) {
    id
    name
    fullName
    email
  }
}

mutation previewResume(
  $resumeTemplateName: ResumeTemplate!
  $personalInfo: ResumePersonalInfo!
  $workExperiences: [ResumeWorkExperience!]! = []
  $projects: [ResumeProject!] = []
  $educations: [ResumeEducation!] = []
  $languageSkillIds: [String!] = []
  $skillIds: [String!] = []
  $skillContents: [String!] = []
  $certificates: [ResumeCertificate!] = []
  $socials: [ResumeSocial!] = []
  $activities: [ResumeActivity!] = []
) {
  preview_resume(
    resumeTemplateName: $resumeTemplateName
    personalInfo: $personalInfo
    workExperiences: $workExperiences
    projects: $projects
    educations: $educations
    languageSkillIds: $languageSkillIds
    skillIds: $skillIds,
    skillContents: $skillContents
    certificates: $certificates
    socials: $socials
    activities: $activities
  ) {
    pdfBase64
    imgBase64
  }
}

query myResume(
  $where: ResumeWhereInput
  $orderBy: [ResumeOrderByWithRelationInput!]
  $searchValue: String
  $pagination: PaginationInput
) {
  my_resume(where: $where, orderBy: $orderBy, searchValue: $searchValue, pagination: $pagination) {
    data {
      id
      name
      fullName
      email
      thumbnail {
        url
      }
      createdAt
    }
    metadata {
      ...Metadata
    }
  }
}
