export type MetaExtractInfo = {
  themeColor: string;
  title: string;
  description: string;
  keywords: string;
  ogSiteName: string;
  ogUrl: string;
  ogTitle: string;
  ogImage: string;
  ogImageWidth: string;
  ogImageHeight: string;
  ogDescription: string;
  alIosAppStoreId: string;
  alIosAppName: string;
  alIosUrl: string;
  alAndroidUrl: string;
  alWebUrl: string;
  ogType: string;
  ogVideoUrl: string;
  ogVideoSecureUrl: string;
  ogVideoType: string;
  ogVideoWidth: string;
  ogVideoHeight: string;
  alAndroidAppName: string;
  alAndroidPackage: string;
  ogVideoTag: string;
  fbAppId: string;
  twitterCard: string;
  twitterSite: string;
  twitterUrl: string;
  twitterTitle: string;
  twitterDescription: string;
  twitterImage: string;
  twitterAppNameIphone: string;
  twitterAppIdIphone: string;
  twitterAppNameIpad: string;
  twitterAppIdIpad: string;
  twitterAppUrlIphone: string;
  twitterAppUrlIpad: string;
  twitterAppNameGoogleplay: string;
  twitterAppIdGoogleplay: string;
  twitterAppUrlGoogleplay: string;
  twitterPlayer: string;
  twitterPlayerWidth: string;
  twitterPlayerHeight: string;
};

export type MetaInfo = {
  title: string;
  description: string;
  imageUrl?: string;
  url: string;
  originUrl: string;
};
