mutation createCompany($input: CreateCompanyInput!) {
  create_company(data: $input) {
    name
    slug
    addressDetail
    description
    createdAt
    updatedAt
    deletedAt
    avatar {
      ...Image
    }
    type {
      id
    }
    size {
      id
    }
    photos {
      ...Image
    }
    address {
      id
    }
    industries {
      id
    }
    social {
      id
      url
    }
  }
}

mutation createJob($data: CreateJobInput!) {
  create_job(data: $data) {
    slug
    description
    type
    salary
    company {
      id
    }
    skills {
      id
    }
    level
    address {
      id
    }
    jobCategory {
      id
    }
    salaryMetadata
  }
}

query myJob(
  $where: JobWhereInput
  $orderBy: [JobOrderByWithRelationInput!]
  $searchValue: String
  $pagination: PaginationInput
) {
  my_job(where: $where, orderBy: $orderBy, searchValue: $searchValue, pagination: $pagination) {
    metadata {
      total
      page
      limit
    }
    data {
      id
      jobTitle {
        name
      }
      slug
      description
      numberOfRecruits
      applicationDeadline
      type
      salary
      company {
        id
        name
      }
      type
      skills {
        id
      }
      level
      address {
        id
      }
      jobCategory {
        id
        name
      }
      salaryMetadata
      address {
        id
        name
        stateName
        countryName
      }
    }
  }
}

mutation deleteJob($where: JobWhereUniqueInput!) {
  delete_job(where: $where) {
    id
    jobTitle {
      name
    }
    slug
    description
    numberOfRecruits
    applicationDeadline
    type
    salary
  }
}
